server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://muirwoods-loki:3100/loki/api/v1/push

scrape_configs:
- job_name: muirwoods_gitlab_access
  static_configs:
  - targets:
      - localhost
    labels:
      job: muirwoods_gitlab_access
      hostname: eve
      __path__: /tmp/nginx_gitlab/gitlab_access.log
  pipeline_stages:
  - match:
      selector: '{job="muirwoods_gitlab_access"}'
      stages:
        - drop:
            expression: '/lfs/'
  - match:
      selector: '{job="muirwoods_gitlab_access"}'
      stages:
        - drop:
            expression: '/gitlab-lfs/'
  - regex:
      expression: '^(?P<ip>\S+) - (?P<user>\S+) \[(?P<time>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<size>\d+) "(?P<referrer>[^"]*)" "(?P<user_agent>[^"]*)" -'
  - labels:
      ip:
      user:
      method:
      path:
      protocol:
      status:
      referrer:
      user_agent:
  - timestamp:
      source: time
      format: 02/Jan/2006:15:04:05 +0000
  - regex:
      source: path
      expression: '/repos/(?P<group>[^/]+)/(?P<repo>[^/]+)\.git'
  - labels:
      group:
      repo:
  - match:
      selector: '{repo=""}'
      action: drop
  - match:
      selector: '{user=~"^\\s*$"}'
      action: drop
  - match:
      selector: '{user="-"}'
      action: drop            
