version: "3"

networks:
  loki:

services:
  muirwoods-loki:
    image: grafana/loki:2.9.2
    ports:
      - "33100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${HOME}/data/loki:/loki
    networks:
      - loki
  muirwoods-repo-log-collector-promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - /home/loki_deployment/data/gitlab_home/logs/nginx:/tmp/nginx_gitlab
      - ./config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
  muirwoods-grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://muirwoods-loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "33000:3000"
    volumes:
      - ${HOME}/data/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - loki
